export const CHANGE_THEME = 'CHANGE_THEME';

export const LIST_ALL = 'LIST_ALL';

export const LIST_CART = 'LIST_CART';
export const ADD_TO_CART = 'ADD_TO_CART';

export const LIST_EMPLOYEES = 'LIST_EMPLOYEES';
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const EDIT_EMPLOYEE = 'EDIT_EMPLOYEE';

export const ADD_RECRUITMENT = 'ADD_RECRUITMENT';
export const LIST_RECRUITMENT = 'LIST_RECRUITMENT';
export const EDIT_RECRUITMENT = 'EDIT_RECRUITMENT';
export const DELETE_RECRUITMENT = 'DELETE_RECRUITMENT';

export const OPEN_FORM_VERSION = 'OPEN_FORM_VERSION';
export const OPEN_FORM_EDIT_VERSION = 'OPEN_FORM_EDIT_VERSION';
export const CLOSE_FORM_VERSION = 'CLOSE_FORM_VERSION';

export const OPEN_FORM_HOT = 'OPEN_FORM_HOT';
export const CLOSE_FORM_HOT = 'CLOSE_FORM_HOT';

export const OPEN_FORM_STORE = 'OPEN_FORM_STORE';
export const CLOSE_FORM_STORE = 'CLOSE_FORM_STORE';


export const OPENFORM = 'OPENFORM';
export const OPEN_FORM_RECRUITMENT = 'OPEN_FORM_RECRUITMENT';
export const CLOSE_FORM_RECRUITMENT = 'CLOSE_FORM_RECRUITMENT';
export const UPDATE_FORM_RECRUITMENT = 'UPDATE_FORM_RECRUITMENT';

export const OPEN_FORM_WHEN_EDIT = 'OPEN_FORM_WHEN_EDIT';
export const CLOSEFORM = 'CLOSEFORM';
export const UPDATEFORM = 'UPDATEFORM';
export const UPDATE_FORM_EMPLOYEE = 'UPDATE_FORM_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';

export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_VERSION = 'ADD_VERSION';
export const LIST_ALL_VERSION = 'LIST_ALL_VERSION';
export const DELETE_VERSION = 'DELETE_VERSION';
export const EDIT_VERSION = 'EDIT_VERSION';
export const UPDATE_VERSION = 'UPDATE_VERSION';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

export const ADD_PRODUCT_IN_STORE = 'ADD_PRODUCT_IN_STORE';
export const LIST_PRODUCT_IN_STORE = 'LIST_PRODUCT_IN_STORE';

export const UPDATE_STATUS_VERSION_HOT = 'UPDATE_STATUS_VERSION_HOT';
export const UPDATE_STATUS_VERSION_SALE = 'UPDATE_STATUS_VERSION_SALE';

export const LIST_FROM_BILL = 'LIST_FROM_BILL';
export const ADD_FROM_BILL = 'ADD_FROM_BILL';
export const DELETE_BILL = 'DELETE_BILL';
export const UPDATE_STATUS = 'UPDATE_STATUS';
export const UPDATE_STATUS_SALE = 'UPDATE_STATUS_SALE';

export const FILTER_TABLE = 'FILTER_TABLE';
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';
export const SORT_PRODUCT = 'SORT_PRODUCT';


